[build]
command = "yarn build"
publish = "public"

[[plugins]]
package = "@netlify/plugin-gatsby"

[[redirects]]
from = "https://departureboard.netlify.app/*"
to = "https://departures.live/:splat"
status = 301
force = true

[[redirects]]
from = "https://departureboard.netlify.app/"
to = "https://departures.live/"
status = 301
force = true
